import reactHooksPlugin from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";
import reactPlugin from "eslint-plugin-react";
import prettierPlugin from "eslint-plugin-prettier";

export default [
  {
    plugins: {
      "@typescript-eslint": tseslint,
      react: reactPlugin,
      "react-hooks": reactHooksPlugin,
      prettier: prettierPlugin,
    },
    languageOptions: {
      parser: tsparser,
      globals: {
        window: "readonly",
        document: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLAnchorElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLFormElement: "readonly",
        Node: "readonly",
        FormData: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        DataTransferItem: "readonly",
        DOMException: "readonly",
        TouchEvent: "readonly",
        ClipboardEvent: "readonly",
        Worker: "readonly",
        WebAssembly: "readonly",
        Headers: "readonly",
        CanvasRenderingContext2D: "readonly",
        self: "readonly",
        require: "readonly",
        __dirname: "readonly",
        process: "readonly",
        module: "readonly",
        console: "readonly",
        jest: "readonly",
        Expect: "readonly",
        Matchers: "readonly",
        React: "readonly",
        KeyboardEvent: "readonly",
        ResizeObserver: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        requestAnimationFrame: "readonly",
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        afterEach: "readonly",
        global: "readonly",
        URL: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Buffer: "readonly",
        FileReader: "readonly",
        CryptoKey: "readonly",
        KeyUsage: "readonly",
        ErrorEvent: "readonly",
        performance: "readonly",
        Image: "readonly",
        queueMicrotask: "readonly",
        URLSearchParams: "readonly",
        HashChangeEvent: "readonly",
        Document: "readonly",
        Window: "readonly",
        FontFace: "readonly",
        FontFaceDescriptors: "readonly",
        Promise: "readonly",
        atob: "readonly",
        btoa: "readonly",
        StructuredSerializeOptions: "readonly",
        vi: "readonly",
        assert: "readonly",
      },
    },
    rules: {
      // Add your TypeScript/React rules here
      "react/jsx-no-target-blank": "warn",
      "prettier/prettier": "warn",
    },
  },
  prettier,
  {
    ignores: ["**/node_modules/**", "**/dist/**", "**/build/**"],
  },
];
